[log]
# support stdout, file, kafka
output = "stdout"
# log level: DEBUG INFO WARNING ERROR FATAL
level = "DEBUG"
# log write directory
path = "logs"
# rotate by time
keepHours = 4
# rotate by size
rotateNum = 3
# unit: MB
rotateSize = 256
# kafka brokers
#kafkaBrokers = [
#    "127.0.0.1:9092",
#    "127.0.0.1:9093",
#    "127.0.0.1:9094"
#]
# kafka topic
# kafkaTopic = ""

[http]
host = "0.0.0.0"
port = 10086
# debug, release
mode = "debug"
# internal context path
# web api context path
internalContextPath = "/v1/"
# external context path
# external api context path
externalContextPath = "/api/"
# unit: second
heartbeat = 60
# enable pprof, false or true
pprof = false
# enable metrics, false or true
exposeMetrics = true
# access log, false or true
accessLog = true
# read timeout
# unit: second
readTimeout = 60
writeTimeout = 60
idleTimeout = 60
shutdownTimeout = 10

[http.tls]
certFile = ''
keyFile = ''

[http.auth]
# jwt access token expire time
# unit: second
accessExpire = 3600
# jwt refresh token expire time
# unit: second
refreshExpire = 7200
secretKey = "bf284d03-ba65-42d4-a9fe-0d2fbfe61060"
# redis in token prefix
redisKey = "auth"

[database]
# support mysql
type = "mysql"
host = "127.0.0.1"
port = "3306"
user = "root"
password = "123456"
db = "arcade_meta"
# sql print, false or true
output = false
# max open connections
# unit: second
maxOpenConns = 500
# max idle connections
# unit: second
maxIdleConns = 5
# max life time
# unit: second
maxLifeTime = 300
# max Idle Time
# unit: second
maxIdleTime = 60

[database.mongo]
# cluster, standalone
# cluster: uri = "mongodb://localhost:27017,localhost:27018,localhost:27019"
# auth: uri = "mongodb://username:password@localhost:27017"
uri = "mongodb://localhost:27017"
compressors = ["snappy", "zstd", "zlib"]
db = "arcade_meta"
poolSize = 100

[redis]
# support single, cluster, sentinel
mode = "single"
# address, ip:port or ip1:port,ip2:port for cluster and sentinel(SentinelAddrs)
address = "0.0.0.0:6379"
password = ""
db = 0
poolSize = 50
#useTLS = false
#tlsMinVersion = "1.0"
#masterName = ""
#sentinelUsername = ""
#sentinelPassword = ""

[minio]
# Tips: Do not use minio user for client authentication, instead create access keys
# https://min.io/docs/minio/container/administration/console/security-and-access.html
accessKeyId = ""
secretAccessKey = ""
endpoint = ""
bucket = ""
useSSL = false
